### ISSUE TITLE
Code doesn't build

### ISSUE THREAD

**Issue by StefanMilne** [cizu64/Coingate.Net#5]
Code doesn't build - does not produce necessary DLL's. Framework issues. Also help file is out of step with actual code. 3 parameter have been change to single token parameter but help and code comments are out of step with new code corrections

**Comment by cizu64** [comment]
It is a console application running on .net core 6. Did you clone it and what version of visual studio are you using?

**Comment by StefanMilne** [comment]
I know. VS12

**Comment by StefanMilne** [comment]
No sorry wrong digit VS2019 not 12

**Comment by cizu64** [comment]
I'll suggest you upgrade to .net 6

**Comment by StefanMilne** [comment]
I downloaded the Zip, ensured I was on .Net Core 6 and it still does not build.

**Comment by cizu64** [comment]
I use visual studio 2022 and target framework .Net 6. Maybe you should be more specific on the kind of errors you are having

**Comment by StefanMilne** [comment]
Maybe you could be more open and attentive with your assistance. My initial statement was that you were using different parameters to call the API and you never replied. Then miraculously a fix was posted. I then tried this fix by downloading it to my VS2019 IDE to find it wont build. I posted that about 3 months ago and again you ignored me. Surely other people must be using your code but i am not finding them.

I will try your code again tomorrow and will post my findings verbatim. I hope you could respond quicker as my boss is quite eager to have this working.

Maybe you could post a video of your code i operation to you tube and I will try and emulate the results.

I find this a suitable suggestion and it will also confirm the API is responding as it should . However I feel the Api is further causing an issue as it seems to fail using the simple curl scripts.

Sincerely 

Stefan

**Comment by cizu64** [comment]
Try to download visual studio 2022 as .Net 6 is not supported in VS2019. You also need to be registered on Coingate to get an API token in order to use the library. You can also issue direct curl command, check out https://developer.coingate.com. When you try the code again, if you get any compilation errors, drop it here, i would respond quickly, sorry for the delay.
